# Generated by Django 4.2.4 on 2023-08-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='products/')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
