# Generated by Django 4.2.4 on 2023-08-14 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_product_writer_alter_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='products/')),
                ('person_name', models.CharField(max_length=100)),
                ('products_name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('hometown', models.CharField(max_length=100)),
                ('organize', models.CharField(max_length=100)),
                ('all_weight', models.FloatField()),
                ('one_weight', models.FloatField()),
                ('description', models.TextField()),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
